repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
            exclude: |
                (?x)^(
                .*\.md|
                )$
          - id: flake8
          - id: check-ast # Valid python files
          - id: mixed-line-ending
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.1.15
      hooks:
          - id: remove-tabs # Changes tabs to spaces
    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
          - id: black
            exclude: ^.*\.md$ # Do not format markdown files
    - repo: https://github.com/PyCQA/isort
      rev: "5.12.0"
      hooks:
          - id: isort
    - repo: https://github.com/PyCQA/pydocstyle
      rev: 6.3.0
      hooks:
          - id: pydocstyle
